name = "BioTechnica-Challenge"
author = "Anhgelus Morhtuuzh"
version = "0.8.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "707180f0f33ba45df90dc9dc235cdef39e72d562e611035f07c85e6218cb3203"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"
