name = "BioTechnica-Challenge"
author = "Anhgelus Morhtuuzh"
version = "0.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd7214b762d24a6592875f2e2ab53cadfdd5cce167311a2caacdcb4fa919125a"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"
