name = "BioTechnica-Challenge"
author = "Anhgelus Morhtuuzh"
version = "0.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2af5780f683e461f6c9b8b70f6e7624278d8794409f93011a79c8988374be96"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"
