name = "BioTechnica-Challenge"
author = "Anhgelus Morhtuuzh"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "744754e3e5ba59c251036774421a3d326c3b58ab2264f1e779a0c5e4b14f8eb7"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
