name = "BioTechnica-Challenge"
author = "Anhgelus Morhtuuzh"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca046978dfa5452cb848c16d61e58d65964dee71aad00b77a58de0561c0496df"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"
