name = "BioTechnica-Challenge"
author = "Anhgelus Morhtuuzh"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33706314264a876acdafd7db7bf7d41d37b256cd3bbcc497ff14845e472df884"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"
