name = "BioTechnica-Challenge"
author = "Anhgelus Morhtuuzh"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "890432e954e7cbade5a67b24ee01d8be0f0378fab40ff0a031c2701324ab6f1e"

[versions]
minecraft = "1.19.4"
quilt = "0.17.6"
