name = "BioTechnica-Challenge"
author = "Anhgelus Morhtuuzh"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee8e377c401b1fc3e3ab48908838894e36d1a7d93c197e009e06ba0715b85c66"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
