name = "BioTechnica-Challenge"
author = "Anhgelus Morhtuuzh"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b8b0f19cedb4788f7c710dc64856cf49fa1820527f18b5ff02203030e2ade6b"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
