name = "BioTechnica-Challenge"
author = "Anhgelus Morhtuuzh"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "505703740376d2c2291cb46b2f1a0f7f025902696eedacbcafabd0689c2f06eb"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"
